name: first workflow
on: workflow_dispatch
jobs:
  onejob:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Run dependencies
        run: npm ci
      - name: Run lint script
        run: npm run lint
      - name: Run test script
        run: npm run test
      - name: Run build scriptgit pull origin master --allow-unrelated-histories
        run: npm run build
      - name: Deploy code
        run: echo "Deploying"